export const refs = {
  article: document.querySelector('#article'),
  spanSize: document.querySelector('#size'),
  readerTools: document.querySelector('.reader-tools'),
  promoDiv: document.querySelector('.promo'),
  clockSpan: document.querySelector('#clock'),
  todaySpan: document.querySelector('#today'),
  greetingTitle: document.querySelector('#greeting'),
  leftSeconds: document.querySelector('#left'),
  stayBtn: document.querySelector('#stay'),
  stayText: document.querySelector('#redirect'),
  messagesField: document.querySelector('#messages'),
  undoBoxField: document.querySelector('#undo-box'),
  undoBtn: document.querySelector('#undo'),
  orderedInput: document.querySelector('#ordered'),
  notifyBtn: document.querySelector('#notify'),
  msg: document.querySelector('#msg'),
  label: document.querySelector('#label'),
  loadBtn: document.querySelector('#load'),
  loader: document.querySelector('.loader'),
  textReport: document.querySelector('#report'),
  profile: document.querySelector('#profile'),
  runButton: document.querySelector('#run'),
  log: document.querySelector('#log'),
};
